/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pss;

import java.util.ArrayList;
import java.util.Random;

/**
 *
 * @author marcus
 */
public class LiftInterface extends javax.swing.JFrame {

    ArrayList<Person> queue;
    LiftController lc1;
    int time; //hhmmss

    /**
     * Creates new form LiftInterface
     */
    public LiftInterface() {
        this.queue = new ArrayList<Person>();
        this.lc1 = new LiftController();
        this.time = 000000;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lift3Bar = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        VVIP = new javax.swing.JButton();
        BlackOps = new javax.swing.JButton();
        Management = new javax.swing.JButton();
        Employee = new javax.swing.JButton();
        Lift1Bar = new javax.swing.JProgressBar();
        Lift2Bar = new javax.swing.JProgressBar();
        Lift5Bar = new javax.swing.JProgressBar();
        Lift4Bar = new javax.swing.JProgressBar();
        Lift1 = new javax.swing.JLabel();
        Lift2 = new javax.swing.JLabel();
        Lift3 = new javax.swing.JLabel();
        Lift4 = new javax.swing.JLabel();
        Lift5 = new javax.swing.JLabel();
        VVIPQueue = new javax.swing.JProgressBar();
        BlackOpsQueue = new javax.swing.JProgressBar();
        ManagementQueue = new javax.swing.JProgressBar();
        EmployeeQueue = new javax.swing.JProgressBar();
        ProcessQueues = new javax.swing.JButton();
        NextStep = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        BlackOpsEmployee = new javax.swing.JButton();
        BlackOpsEmployeeQueue = new javax.swing.JProgressBar();
        RandomButton = new javax.swing.JButton();
        Visitor = new javax.swing.JButton();
        VisitorQueue = new javax.swing.JProgressBar();
        Maintenance = new javax.swing.JButton();
        Cleaner = new javax.swing.JButton();
        MaintenanceQueue = new javax.swing.JProgressBar();
        CleanerQueue = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProcessingStatus = new javax.swing.JTextArea();
        TotalQueue = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        WeekendToggle = new javax.swing.JToggleButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        Lift1Persons = new javax.swing.JLabel();
        Lift2Persons = new javax.swing.JLabel();
        Lift3Persons = new javax.swing.JLabel();
        Lift4Persons = new javax.swing.JLabel();
        Lift5Persons = new javax.swing.JLabel();
        Go = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Lift3Bar.setMaximum(12);
        Lift3Bar.setMinimum(-2);
        Lift3Bar.setOrientation(1);
        Lift3Bar.setToolTipText("");
        Lift3Bar.setValue(1);
        Lift3Bar.setString("1");
        Lift3Bar.setStringPainted(true);

        jButton1.setText("Floor B1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Floor 2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Floor 3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Floor 4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Floor 5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Floor 6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Floor 7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Floor 8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Floor 9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Floor 10");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Floor 11");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Floor 12");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        VVIP.setText("Add 1 VVIP Trip");
        VVIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VVIPActionPerformed(evt);
            }
        });

        BlackOps.setText("Add 1 Black Ops Trip");
        BlackOps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlackOpsActionPerformed(evt);
            }
        });

        Management.setText("Add 1 Management Trip");
        Management.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManagementActionPerformed(evt);
            }
        });

        Employee.setText("Add 1 Employee Trip");
        Employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeActionPerformed(evt);
            }
        });

        Lift1Bar.setMaximum(12);
        Lift1Bar.setMinimum(-2);
        Lift1Bar.setOrientation(1);
        Lift1Bar.setValue(1);
        Lift1Bar.setString("1");
        Lift1Bar.setStringPainted(true);

        Lift2Bar.setMaximum(12);
        Lift2Bar.setMinimum(-2);
        Lift2Bar.setOrientation(1);
        Lift2Bar.setValue(1);
        Lift2Bar.setString("1");
        Lift2Bar.setStringPainted(true);

        Lift5Bar.setMaximum(12);
        Lift5Bar.setMinimum(-2);
        Lift5Bar.setOrientation(1);
        Lift5Bar.setValue(1);
        Lift5Bar.setString("1");
        Lift5Bar.setStringPainted(true);

        Lift4Bar.setMaximum(12);
        Lift4Bar.setMinimum(-2);
        Lift4Bar.setOrientation(1);
        Lift4Bar.setValue(1);
        Lift4Bar.setString("1");
        Lift4Bar.setStringPainted(true);

        Lift1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lift1.setText("Lift 1");

        Lift2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lift2.setText("Lift 2");

        Lift3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lift3.setText("Lift 3");

        Lift4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lift4.setText("Lift 4");

        Lift5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lift5.setText("Lift 5");

        VVIPQueue.setMaximum(10000);
        VVIPQueue.setString("0");
        VVIPQueue.setStringPainted(true);

        BlackOpsQueue.setMaximum(10000);
        BlackOpsQueue.setString("0");
        BlackOpsQueue.setStringPainted(true);

        ManagementQueue.setMaximum(10000);
        ManagementQueue.setString("0");
        ManagementQueue.setStringPainted(true);

        EmployeeQueue.setMaximum(10000);
        EmployeeQueue.setString("0");
        EmployeeQueue.setStringPainted(true);

        ProcessQueues.setText("Process Queues");
        ProcessQueues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcessQueuesActionPerformed(evt);
            }
        });

        NextStep.setText("Next Step");
        NextStep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextStepActionPerformed(evt);
            }
        });

        ClearButton.setText("Clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        BlackOpsEmployee.setText("Add 1 Black Ops Employee Trip");
        BlackOpsEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlackOpsEmployeeActionPerformed(evt);
            }
        });

        BlackOpsEmployeeQueue.setMaximum(10000);
        BlackOpsEmployeeQueue.setString("0");
        BlackOpsEmployeeQueue.setStringPainted(true);

        RandomButton.setText("Randomise Queues");
        RandomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RandomButtonActionPerformed(evt);
            }
        });

        Visitor.setText("Add 1 Visitor Trip");
        Visitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisitorActionPerformed(evt);
            }
        });

        VisitorQueue.setMaximum(10000);
        VisitorQueue.setString("0");
        VisitorQueue.setStringPainted(true);

        Maintenance.setText("Add 1 Maintenance Trip");
        Maintenance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaintenanceActionPerformed(evt);
            }
        });

        Cleaner.setText("Add 1 Cleaner Trip");
        Cleaner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CleanerActionPerformed(evt);
            }
        });

        MaintenanceQueue.setMaximum(10000);
        MaintenanceQueue.setString("0");
        MaintenanceQueue.setStringPainted(true);

        CleanerQueue.setMaximum(10000);
        CleanerQueue.setString("0");
        CleanerQueue.setStringPainted(true);

        ProcessingStatus.setColumns(15);
        ProcessingStatus.setLineWrap(true);
        ProcessingStatus.setRows(5);
        ProcessingStatus.setText("Choose your poison.");
        jScrollPane1.setViewportView(ProcessingStatus);

        TotalQueue.setMaximum(800);
        TotalQueue.setString("0");
        TotalQueue.setStringPainted(true);

        jLabel1.setText("Total:");

        WeekendToggle.setText("Weekend");
        WeekendToggle.setToolTipText("Aiyah, ask you go weekend break also ask for help. Sibei bodoh.");

        jButton13.setText("Floor 1");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("Floor B2");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        Lift1Persons.setText("0");

        Lift2Persons.setText("0");

        Lift3Persons.setText("0");

        Lift4Persons.setText("0");

        Lift5Persons.setText("0");

        Go.setText("Go");
        Go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoActionPerformed(evt);
            }
        });

        jLabel2.setText("Time:");

        Time.setText("000000");

        jButton15.setText("Scenario 1");

        jButton16.setText("Scenario 2");

        jButton17.setText("Scenario 3");

        jButton18.setText("Scenario 4");

        jButton19.setText("Scenario 5");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(14, 14, 14)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, jButton14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(jButton7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jButton8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jButton9, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jButton10, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jButton11, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, jButton12, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, jButton6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, jButton13, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, jButton2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, jButton3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, jButton4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, jButton5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(VVIP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 146, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(BlackOps))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(BlackOpsQueue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(VVIPQueue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, Go, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(NextStep, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                .add(ProcessQueues, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                .add(ClearButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, RandomButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, Cleaner, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, Maintenance, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, Visitor, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, BlackOpsEmployee, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, Employee, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .add(Management, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, TotalQueue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, EmployeeQueue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(BlackOpsEmployeeQueue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(VisitorQueue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(MaintenanceQueue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(CleanerQueue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel1)
                            .add(ManagementQueue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 357, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 3, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(9, 9, 9)
                        .add(Lift1Bar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(Lift1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(Lift1Persons, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(30, 30, 30)
                        .add(Lift2Bar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(12, 12, 12)
                        .add(Lift2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(Lift2Persons, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 71, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(9, 9, 9)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(30, 30, 30)
                        .add(Lift3Bar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(53, 53, 53)
                        .add(Lift4Bar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(Lift5Bar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(30, 30, 30)
                                .add(jLabel2)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(Time)
                                .add(14, 14, 14))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(18, 18, 18)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                        .add(jButton16)
                                        .add(6, 6, 6))
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jButton15)
                                            .add(org.jdesktop.layout.GroupLayout.TRAILING, WeekendToggle))
                                        .addContainerGap())
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                        .add(jButton17)
                                        .addContainerGap())
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                        .add(jButton18)
                                        .addContainerGap())
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                        .add(jButton19)
                                        .addContainerGap())))))
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(Lift3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(Lift3Persons, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 72, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(Lift4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(Lift4Persons, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(Lift5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(Lift5Persons, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(119, 119, 119))))
        );

        layout.linkSize(new java.awt.Component[] {BlackOps, BlackOpsEmployee, ClearButton, Employee, Management, NextStep, ProcessQueues, VVIP}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.linkSize(new java.awt.Component[] {Lift1Bar, Lift2Bar, Lift3Bar, Lift4Bar, Lift5Bar}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.linkSize(new java.awt.Component[] {WeekendToggle, jButton15, jButton16, jButton17, jButton18, jButton19}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(Lift2Bar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 236, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Lift3Bar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 236, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Lift4Bar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 236, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Lift5Bar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 236, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Lift1Bar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 236, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(WeekendToggle)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel2)
                            .add(Time))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton15)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton16)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton17)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton18)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton19)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(Lift1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Lift2)
                    .add(Lift3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Lift4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Lift1Persons)
                    .add(Lift2Persons)
                    .add(Lift3Persons)
                    .add(Lift4Persons)
                    .add(Lift5)
                    .add(Lift5Persons))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(BlackOps)
                                    .add(BlackOpsQueue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(VVIP)
                                    .add(VVIPQueue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(Management)
                                    .add(ManagementQueue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(BlackOpsEmployeeQueue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(BlackOpsEmployee))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(EmployeeQueue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(Employee))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(VisitorQueue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(Visitor))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(MaintenanceQueue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(Maintenance))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(CleanerQueue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(Cleaner))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(RandomButton)
                                        .add(6, 6, 6))
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                        .add(jLabel1)
                                        .add(18, 18, 18)))
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(ClearButton)
                                    .add(layout.createSequentialGroup()
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                            .add(TotalQueue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(ProcessQueues))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(NextStep)
                                        .add(35, 35, 35))))
                            .add(layout.createSequentialGroup()
                                .add(jButton14)
                                .add(5, 5, 5)
                                .add(jButton1)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jButton13)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jButton2)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jButton3)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jButton4)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jButton5)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jButton6)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jButton7)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jButton8)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jButton9)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jButton10)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jButton11)
                                    .add(Go))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jButton12)))
                        .add(0, 18, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {Lift1Bar, Lift2Bar, Lift3Bar, Lift4Bar, Lift5Bar}, org.jdesktop.layout.GroupLayout.VERTICAL);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Lift3Bar.setValue(4);
        Lift3Bar.setString("4");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Lift3Bar.setValue(5);
        Lift3Bar.setString("5");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Lift3Bar.setValue(6);
        Lift3Bar.setString("6");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Lift3Bar.setValue(7);
        Lift3Bar.setString("7");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Lift3Bar.setValue(8);
        Lift3Bar.setString("8");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        Lift3Bar.setValue(9);
        Lift3Bar.setString("9");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        Lift3Bar.setValue(10);
        Lift3Bar.setString("10");
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Lift3Bar.setValue(-1);
        Lift3Bar.setString("B1");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Lift3Bar.setValue(2);
        Lift3Bar.setString("2");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Lift3Bar.setValue(3);
        Lift3Bar.setString("3");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        Lift3Bar.setValue(11);
        Lift3Bar.setString("11");
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        Lift3Bar.setValue(12);
        Lift3Bar.setString("12");
    }//GEN-LAST:event_jButton12ActionPerformed

    private void VVIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VVIPActionPerformed
        VVIPQueue.setValue(VVIPQueue.getValue() + 1);
        VVIPQueue.setString(String.valueOf(VVIPQueue.getValue()));
    }//GEN-LAST:event_VVIPActionPerformed

    private void BlackOpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlackOpsActionPerformed
        BlackOpsQueue.setValue(BlackOpsQueue.getValue() + 1);
        BlackOpsQueue.setString(String.valueOf(BlackOpsQueue.getValue()));
    }//GEN-LAST:event_BlackOpsActionPerformed

    private void ManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManagementActionPerformed
        ManagementQueue.setValue(ManagementQueue.getValue() + 1);
        ManagementQueue.setString(String.valueOf(ManagementQueue.getValue()));
    }//GEN-LAST:event_ManagementActionPerformed

    private void EmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeActionPerformed
        EmployeeQueue.setValue(EmployeeQueue.getValue() + 1);
        EmployeeQueue.setString(String.valueOf(EmployeeQueue.getValue()));
    }//GEN-LAST:event_EmployeeActionPerformed

    private void ProcessQueuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcessQueuesActionPerformed
        //Algorithm starts here
        if (BlackOpsQueue.getValue() > 0) {
            ProcessingStatus.setText("Black Ops\r\n");
        }
        if (VVIPQueue.getValue() > 0) {
            ProcessingStatus.setText(ProcessingStatus.getText() + "VVIP\r\n");
        }
        if (ManagementQueue.getValue() > 0) {
            ProcessingStatus.setText(ProcessingStatus.getText() + "Management\r\n");
        }
        if (BlackOpsEmployeeQueue.getValue() > 0) {
            ProcessingStatus.setText(ProcessingStatus.getText() + "Black Ops Employee\r\n");
        }
        if (EmployeeQueue.getValue() > 0) {
            ProcessingStatus.setText(ProcessingStatus.getText() + "Employee\r\n");
        }
        if (VisitorQueue.getValue() > 0) {
            ProcessingStatus.setText(ProcessingStatus.getText() + "Visitor\r\n");
        }
        if (MaintenanceQueue.getValue() > 0) {
            ProcessingStatus.setText(ProcessingStatus.getText() + "Maintenance\r\n");
        }
        if (CleanerQueue.getValue() > 0) {
            ProcessingStatus.setText(ProcessingStatus.getText() + "Cleaner\r\n");
        }
    }//GEN-LAST:event_ProcessQueuesActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        BlackOpsQueue.setValue(0);
        VVIPQueue.setValue(0);
        ManagementQueue.setValue(0);
        BlackOpsEmployeeQueue.setValue(0);
        EmployeeQueue.setValue(0);
        VisitorQueue.setValue(0);
        MaintenanceQueue.setValue(0);
        CleanerQueue.setValue(0);

        BlackOpsQueue.setString("0");
        VVIPQueue.setString("0");
        ManagementQueue.setString("0");
        BlackOpsEmployeeQueue.setString("0");
        EmployeeQueue.setString("0");
        VisitorQueue.setString("0");
        MaintenanceQueue.setString("0");
        CleanerQueue.setString("0");

        ProcessingStatus.setText("");
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void BlackOpsEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlackOpsEmployeeActionPerformed
        BlackOpsEmployeeQueue.setValue(BlackOpsEmployeeQueue.getValue() + 1);
        BlackOpsEmployeeQueue.setString(String.valueOf(BlackOpsEmployeeQueue.getValue()));
    }//GEN-LAST:event_BlackOpsEmployeeActionPerformed

    private void RandomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RandomButtonActionPerformed
        // Randomise the queues according to requirements
        //5% VVIP cannot share lifts due to vvip protocol
        //10% Black ops cannot share lifts but lock down mode

        Random r = new Random();

        if (WeekendToggle.isSelected()) {
            BlackOpsQueue.setValue(r.nextInt(10));
            VVIPQueue.setValue(r.nextInt(1));
            ManagementQueue.setValue(r.nextInt(5));
            BlackOpsEmployeeQueue.setValue(r.nextInt(10));
            EmployeeQueue.setValue(r.nextInt(20));
            VisitorQueue.setValue(r.nextInt(1));
            MaintenanceQueue.setValue(r.nextInt(100));
            CleanerQueue.setValue(r.nextInt(50) + 50);
        } else {
            BlackOpsQueue.setValue(r.nextInt(10000));
            VVIPQueue.setValue(r.nextInt(10000));
            ManagementQueue.setValue(r.nextInt(10000));
            BlackOpsEmployeeQueue.setValue(r.nextInt(10000));
            EmployeeQueue.setValue(r.nextInt(10000));
            VisitorQueue.setValue(r.nextInt(10000));
            MaintenanceQueue.setValue(r.nextInt(10000));
            CleanerQueue.setValue(r.nextInt(10000));
        }

        BlackOpsQueue.setString(String.valueOf(BlackOpsQueue.getValue()));
        VVIPQueue.setString(String.valueOf(VVIPQueue.getValue()));
        ManagementQueue.setString(String.valueOf(ManagementQueue.getValue()));
        BlackOpsEmployeeQueue.setString(String.valueOf(BlackOpsEmployeeQueue.getValue()));
        EmployeeQueue.setString(String.valueOf(EmployeeQueue.getValue()));
        VisitorQueue.setString(String.valueOf(VisitorQueue.getValue()));
        MaintenanceQueue.setString(String.valueOf(MaintenanceQueue.getValue()));
        CleanerQueue.setString(String.valueOf(CleanerQueue.getValue()));

        for (int i = 0; i < BlackOpsQueue.getValue(); i++) {
            queue.add(new Person(1));
        }
        for (int i = 0; i < VVIPQueue.getValue(); i++) {
            queue.add(new Person(2));
        }
        for (int i = 0; i < ManagementQueue.getValue(); i++) {
            queue.add(new Person(3));
        }
        for (int i = 0; i < BlackOpsEmployeeQueue.getValue(); i++) {
            queue.add(new Person(4));
        }
        for (int i = 0; i < EmployeeQueue.getValue(); i++) {
            queue.add(new Person(5));
        }
        for (int i = 0; i < VisitorQueue.getValue(); i++) {
            queue.add(new Person(6));
        }
        for (int i = 0; i < MaintenanceQueue.getValue(); i++) {
            queue.add(new Person(7));
        }
        for (int i = 0; i < CleanerQueue.getValue(); i++) {
            queue.add(new Person(8));
        }
        ProcessingStatus.setText("");

        int i = 0;
        for (Person person : queue) {
            if (person.getTiming() == i) {
                ProcessingStatus.setText(ProcessingStatus.getText() + person.getTypeName() + " " + person.getTiming() + " \r\n");
            }
            i++;
        }
        ProcessingStatus.setText(ProcessingStatus.getText() + "Total in queue: " + queue.size() + " \r\n");

    }//GEN-LAST:event_RandomButtonActionPerformed

    private void VisitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisitorActionPerformed
        VisitorQueue.setValue(VisitorQueue.getValue() + 1);
        VisitorQueue.setString(String.valueOf(VisitorQueue.getValue()));
    }//GEN-LAST:event_VisitorActionPerformed

    private void MaintenanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaintenanceActionPerformed
        MaintenanceQueue.setValue(MaintenanceQueue.getValue() + 1);
        MaintenanceQueue.setString(String.valueOf(MaintenanceQueue.getValue()));
    }//GEN-LAST:event_MaintenanceActionPerformed

    private void CleanerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CleanerActionPerformed
        CleanerQueue.setValue(CleanerQueue.getValue() + 1);
        CleanerQueue.setString(String.valueOf(CleanerQueue.getValue()));
    }//GEN-LAST:event_CleanerActionPerformed

    private void NextStepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextStepActionPerformed
        //if queue contains black ops
        //have boolean for only management and black ops until its cleared
        boolean gotManagementOrBlackOps = false;

        //check all lifts
        for (int i = 0; i < queue.size(); i++) {
            if (queue.get(i).getType() == 4) {
                if (queue.get(i).getTiming() < time) {
                    gotManagementOrBlackOps = true;
                    break;
                }
            }
        }

        ArrayList<Person> allInLiftQueues = new ArrayList<Person>();
        allInLiftQueues.addAll(lc1.getLift1().getPersons());
        allInLiftQueues.addAll(lc1.getLift2().getPersons());
        allInLiftQueues.addAll(lc1.getLift3().getPersons());
        allInLiftQueues.addAll(lc1.getLift4().getPersons());
        allInLiftQueues.addAll(lc1.getLift5().getPersons());
        allInLiftQueues.addAll(lc1.getLift1().personsToPickUp);
        allInLiftQueues.addAll(lc1.getLift2().personsToPickUp);
        allInLiftQueues.addAll(lc1.getLift3().personsToPickUp);
        allInLiftQueues.addAll(lc1.getLift4().personsToPickUp);
        allInLiftQueues.addAll(lc1.getLift5().personsToPickUp);
        for (int i = 0; i < allInLiftQueues.size(); i++) {
            if (queue.get(i).getType() == 4) {
                gotManagementOrBlackOps = true;
                break;
            }
        }

        for (int i = 0; i < queue.size(); i++) {
            if (gotManagementOrBlackOps == false) {
                if (queue.get(i).getTiming() < time) {
                    if (lc1.pickUp(queue.get(i))) {
                        ProcessingStatus.setText(ProcessingStatus.getText() + queue.get(i).getTypeName() + " entered at " + queue.get(i).timing + " \r\n");
                        queue.remove(i);
                    }
                }
            } else {
                if (queue.get(i).getType() == 4 || queue.get(i).getType() == 3) {
                    if (queue.get(i).getTiming() < time) {
                        if (lc1.pickUp(queue.get(i))) {
                            ProcessingStatus.setText(ProcessingStatus.getText() + "Black Ops Lockdown at " + queue.get(i).timing + " \r\n");
                            queue.remove(i);
                        }
                    }
                }
            }
        }

        time = time + 5; //adds 5 seconds to the clock each time

        Time.setText(String.valueOf(time));
        Lift1Bar.setValue(lc1.liftGetNextStep(1));
        Lift1Bar.setString(String.valueOf(lc1.liftGetNextStep(1)));
        Lift1Persons.setText(lc1.getLift1().getDirection() + " " + String.valueOf(lc1.liftGetNumberOfPersons(1)));
        Lift2Bar.setValue(lc1.liftGetNextStep(2));
        Lift2Bar.setString(String.valueOf(lc1.liftGetNextStep(2)));
        Lift2Persons.setText(lc1.getLift2().getDirection() + " " + String.valueOf(lc1.liftGetNumberOfPersons(2)));
        Lift3Bar.setValue(lc1.liftGetNextStep(3));
        Lift3Bar.setString(String.valueOf(lc1.liftGetNextStep(3)));
        Lift3Persons.setText(lc1.getLift3().getDirection() + " " + String.valueOf(lc1.liftGetNumberOfPersons(3)));
        Lift4Bar.setValue(lc1.liftGetNextStep(4));
        Lift4Bar.setString(String.valueOf(lc1.liftGetNextStep(4)));
        Lift4Persons.setText(lc1.getLift4().getDirection() + " " + String.valueOf(lc1.liftGetNumberOfPersons(4)));
        Lift5Bar.setValue(lc1.liftGetNextStep(5));
        Lift5Bar.setString(String.valueOf(lc1.liftGetNextStep(5)));
        Lift5Persons.setText(lc1.getLift5().getDirection() + " " + String.valueOf(lc1.liftGetNumberOfPersons(5)));
        
        for (int i = 0; i < lc1.getLift1().getPersons().size(); i++) {
            ProcessingStatus.setText(ProcessingStatus.getText() + time + " Lift 1 has a " + lc1.getLift1().getPersons().get(i).getTypeName() + " \r\n");
        }
        for (int i = 0; i < lc1.getLift2().getPersons().size(); i++) {
            ProcessingStatus.setText(ProcessingStatus.getText() + time + " Lift 2 has a " + lc1.getLift2().getPersons().get(i).getTypeName() + " \r\n");
        }
        for (int i = 0; i < lc1.getLift3().getPersons().size(); i++) {
            ProcessingStatus.setText(ProcessingStatus.getText() + time + " Lift 3 has a " + lc1.getLift3().getPersons().get(i).getTypeName() + " \r\n");
        }
        for (int i = 0; i < lc1.getLift4().getPersons().size(); i++) {
            ProcessingStatus.setText(ProcessingStatus.getText() + time + " Lift 4 has a " + lc1.getLift4().getPersons().get(i).getTypeName() + " \r\n");
        }
        for (int i = 0; i < lc1.getLift5().getPersons().size(); i++) {
            ProcessingStatus.setText(ProcessingStatus.getText() + time + " Lift 5 has a " + lc1.getLift5().getPersons().get(i).getTypeName() + " \r\n");
        }
        
    }//GEN-LAST:event_NextStepActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        Lift3Bar.setValue(1);
        Lift3Bar.setString("1");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        Lift3Bar.setValue(-2);
        Lift3Bar.setString("B2");
    }//GEN-LAST:event_jButton14ActionPerformed

    private void GoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoActionPerformed
        for (int i = 0; i < 48000; i++) {
            NextStepActionPerformed(null);
        }
    }//GEN-LAST:event_GoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LiftInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LiftInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LiftInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LiftInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LiftInterface().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BlackOps;
    private javax.swing.JButton BlackOpsEmployee;
    private javax.swing.JProgressBar BlackOpsEmployeeQueue;
    private javax.swing.JProgressBar BlackOpsQueue;
    private javax.swing.JButton Cleaner;
    private javax.swing.JProgressBar CleanerQueue;
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton Employee;
    private javax.swing.JProgressBar EmployeeQueue;
    private javax.swing.JButton Go;
    private javax.swing.JLabel Lift1;
    private javax.swing.JProgressBar Lift1Bar;
    private javax.swing.JLabel Lift1Persons;
    private javax.swing.JLabel Lift2;
    private javax.swing.JProgressBar Lift2Bar;
    private javax.swing.JLabel Lift2Persons;
    private javax.swing.JLabel Lift3;
    private javax.swing.JProgressBar Lift3Bar;
    private javax.swing.JLabel Lift3Persons;
    private javax.swing.JLabel Lift4;
    private javax.swing.JProgressBar Lift4Bar;
    private javax.swing.JLabel Lift4Persons;
    private javax.swing.JLabel Lift5;
    private javax.swing.JProgressBar Lift5Bar;
    private javax.swing.JLabel Lift5Persons;
    private javax.swing.JButton Maintenance;
    private javax.swing.JProgressBar MaintenanceQueue;
    private javax.swing.JButton Management;
    private javax.swing.JProgressBar ManagementQueue;
    private javax.swing.JButton NextStep;
    private javax.swing.JButton ProcessQueues;
    private javax.swing.JTextArea ProcessingStatus;
    private javax.swing.JButton RandomButton;
    private javax.swing.JLabel Time;
    private javax.swing.JProgressBar TotalQueue;
    private javax.swing.JButton VVIP;
    private javax.swing.JProgressBar VVIPQueue;
    private javax.swing.JButton Visitor;
    private javax.swing.JProgressBar VisitorQueue;
    private javax.swing.JToggleButton WeekendToggle;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
