/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pss;

import java.util.ArrayList;
import java.util.Random;

/**
 *
 * @author marcus
 */
public class LiftInterface extends javax.swing.JFrame {
    
    ArrayList<PersonTiming> queue;
    
    /**
     * Creates new form LiftInterface
     */
    public LiftInterface() {
        this.queue = new ArrayList<PersonTiming>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DoorOpenButton = new javax.swing.JButton();
        DoorCloseButton = new javax.swing.JButton();
        EmergencyAlarmButton = new javax.swing.JButton();
        IntercomButton = new javax.swing.JButton();
        Lift1Bar = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        VVIP = new javax.swing.JButton();
        BlackOps = new javax.swing.JButton();
        Management = new javax.swing.JButton();
        Employee = new javax.swing.JButton();
        Lift1Bar1 = new javax.swing.JProgressBar();
        Lift1Bar2 = new javax.swing.JProgressBar();
        Lift1Bar3 = new javax.swing.JProgressBar();
        Lift1Bar4 = new javax.swing.JProgressBar();
        Lift1 = new javax.swing.JLabel();
        Lift2 = new javax.swing.JLabel();
        Lift3 = new javax.swing.JLabel();
        Lift4 = new javax.swing.JLabel();
        Lift5 = new javax.swing.JLabel();
        VVIPQueue = new javax.swing.JProgressBar();
        BlackOpsQueue = new javax.swing.JProgressBar();
        ManagementQueue = new javax.swing.JProgressBar();
        EmployeeQueue = new javax.swing.JProgressBar();
        ProcessQueues = new javax.swing.JButton();
        NextStep = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        BlackOpsEmployee = new javax.swing.JButton();
        BlackOpsEmployeeQueue = new javax.swing.JProgressBar();
        RandomButton = new javax.swing.JButton();
        Visitor = new javax.swing.JButton();
        VisitorQueue = new javax.swing.JProgressBar();
        Maintenance = new javax.swing.JButton();
        Cleaner = new javax.swing.JButton();
        MaintenanceQueue = new javax.swing.JProgressBar();
        CleanerQueue = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProcessingStatus = new javax.swing.JTextArea();
        TotalQueue = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        WeekendToggle = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DoorOpenButton.setText("Door Open");
        DoorOpenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoorOpenButtonActionPerformed(evt);
            }
        });

        DoorCloseButton.setText("Door Close");

        EmergencyAlarmButton.setText("Emergency Alarm");

        IntercomButton.setText("Intercom");

        Lift1Bar.setMaximum(12);
        Lift1Bar.setOrientation(1);
        Lift1Bar.setToolTipText("");
        Lift1Bar.setValue(1);

        jButton1.setText("Floor 1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Floor 2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Floor 3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Floor 4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Floor 5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Floor 6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Floor 7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Floor 8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Floor 9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Floor 10");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Floor 11");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Floor 12");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        VVIP.setText("Add 1 VVIP");
        VVIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VVIPActionPerformed(evt);
            }
        });

        BlackOps.setText("Add 1 Black Ops");
        BlackOps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlackOpsActionPerformed(evt);
            }
        });

        Management.setText("Add 1 Management");
        Management.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManagementActionPerformed(evt);
            }
        });

        Employee.setText("Add 1 Employee");
        Employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeActionPerformed(evt);
            }
        });

        Lift1Bar1.setMaximum(12);
        Lift1Bar1.setOrientation(1);
        Lift1Bar1.setValue(1);

        Lift1Bar2.setMaximum(12);
        Lift1Bar2.setOrientation(1);
        Lift1Bar2.setValue(1);

        Lift1Bar3.setMaximum(12);
        Lift1Bar3.setOrientation(1);
        Lift1Bar3.setValue(1);

        Lift1Bar4.setMaximum(12);
        Lift1Bar4.setOrientation(1);
        Lift1Bar4.setValue(1);

        Lift1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lift1.setText("Lift 1");

        Lift2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lift2.setText("Lift 2");

        Lift3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lift3.setText("Lift 3");

        Lift4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lift4.setText("Lift 4");

        Lift5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lift5.setText("Lift 5");

        VVIPQueue.setString("0");
        VVIPQueue.setStringPainted(true);

        BlackOpsQueue.setString("0");
        BlackOpsQueue.setStringPainted(true);

        ManagementQueue.setString("0");
        ManagementQueue.setStringPainted(true);

        EmployeeQueue.setString("0");
        EmployeeQueue.setStringPainted(true);

        ProcessQueues.setText("Process Queues");
        ProcessQueues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcessQueuesActionPerformed(evt);
            }
        });

        NextStep.setText("Next Step");
        NextStep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextStepActionPerformed(evt);
            }
        });

        ClearButton.setText("Clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        BlackOpsEmployee.setText("Add 1 Black Ops Employee");
        BlackOpsEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlackOpsEmployeeActionPerformed(evt);
            }
        });

        BlackOpsEmployeeQueue.setString("0");
        BlackOpsEmployeeQueue.setStringPainted(true);

        RandomButton.setText("Randomise Queues");
        RandomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RandomButtonActionPerformed(evt);
            }
        });

        Visitor.setText("Add 1 Visitor");
        Visitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisitorActionPerformed(evt);
            }
        });

        VisitorQueue.setString("0");
        VisitorQueue.setStringPainted(true);

        Maintenance.setText("Add 1 Maintenance");
        Maintenance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaintenanceActionPerformed(evt);
            }
        });

        Cleaner.setText("Add 1 Cleaner");
        Cleaner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CleanerActionPerformed(evt);
            }
        });

        MaintenanceQueue.setString("0");
        MaintenanceQueue.setStringPainted(true);

        CleanerQueue.setString("0");
        CleanerQueue.setStringPainted(true);

        ProcessingStatus.setColumns(15);
        ProcessingStatus.setLineWrap(true);
        ProcessingStatus.setRows(5);
        ProcessingStatus.setText("Choose your poison.");
        jScrollPane1.setViewportView(ProcessingStatus);

        TotalQueue.setMaximum(800);
        TotalQueue.setString("0");
        TotalQueue.setStringPainted(true);

        jLabel1.setText("Total:");

        WeekendToggle.setText("Weekend");
        WeekendToggle.setToolTipText("Aiyah, ask you go weekend break also ask for help. Sibei bodoh.");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(EmergencyAlarmButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(IntercomButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(DoorCloseButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(DoorOpenButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(Lift1Bar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(166, 166, 166)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jButton1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jButton2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jButton3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jButton4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jButton5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jButton6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jButton7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jButton8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jButton9, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jButton10, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jButton11, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jButton12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .add(156, 156, 156)
                        .add(Lift1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(NextStep, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 165, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(layout.createSequentialGroup()
                                .add(ProcessQueues, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 165, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(TotalQueue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(ClearButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 165, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, RandomButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, Cleaner, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, Maintenance, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, Visitor, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, BlackOpsEmployee, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, Employee, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(EmployeeQueue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(BlackOpsEmployeeQueue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(VisitorQueue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(MaintenanceQueue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(CleanerQueue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabel1)))
                            .add(layout.createSequentialGroup()
                                .add(Management)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(ManagementQueue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(VVIP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 146, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(BlackOps))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(BlackOpsQueue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(VVIPQueue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(layout.createSequentialGroup()
                            .add(Lift2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(145, 145, 145)
                            .add(Lift4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 89, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                            .add(Lift5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 89, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(layout.createSequentialGroup()
                            .add(Lift1Bar2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(layout.createSequentialGroup()
                                    .add(Lift3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 91, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(0, 0, Short.MAX_VALUE))
                                .add(layout.createSequentialGroup()
                                    .add(Lift1Bar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                    .add(Lift1Bar4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(Lift1Bar3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(WeekendToggle))))))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {BlackOps, BlackOpsEmployee, ClearButton, Employee, Management, NextStep, ProcessQueues, VVIP}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.linkSize(new java.awt.Component[] {Lift1Bar, Lift1Bar1, Lift1Bar2, Lift1Bar3, Lift1Bar4}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(DoorOpenButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(DoorCloseButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(EmergencyAlarmButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(IntercomButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(Lift1Bar2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 236, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Lift1Bar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 236, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Lift1Bar4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 236, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Lift1Bar3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 236, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Lift1Bar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 236, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(WeekendToggle))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(Lift1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Lift2)
                    .add(Lift3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Lift4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Lift5))
                .add(21, 21, 21)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jButton1)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jButton2)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 8, Short.MAX_VALUE)
                                .add(jButton3)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jButton4)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jButton5))
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(BlackOps)
                                    .add(BlackOpsQueue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(VVIP)
                                    .add(VVIPQueue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                        .add(Management)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                                    .add(layout.createSequentialGroup()
                                        .add(ManagementQueue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(BlackOpsEmployee)
                                    .add(BlackOpsEmployeeQueue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(Employee)
                                    .add(EmployeeQueue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(jButton6)
                                .add(Visitor))
                            .add(VisitorQueue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jButton7)
                                    .add(Maintenance))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jButton8)
                                    .add(Cleaner))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jButton9)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jButton10)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jButton11)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jButton12))
                            .add(layout.createSequentialGroup()
                                .add(MaintenanceQueue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                            .add(RandomButton)
                                            .add(jLabel1))
                                        .add(6, 6, 6))
                                    .add(layout.createSequentialGroup()
                                        .add(15, 15, 15)
                                        .add(CleanerQueue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(TotalQueue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(79, 79, 79))
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                        .add(ClearButton)
                                        .add(layout.createSequentialGroup()
                                            .add(ProcessQueues)
                                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                            .add(NextStep)
                                            .add(35, 35, 35)))))))
                    .add(jScrollPane1))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {Lift1Bar, Lift1Bar1, Lift1Bar2, Lift1Bar3, Lift1Bar4}, org.jdesktop.layout.GroupLayout.VERTICAL);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DoorOpenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoorOpenButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoorOpenButtonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Lift1Bar.setValue(4);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Lift1Bar.setValue(5);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Lift1Bar.setValue(6);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Lift1Bar.setValue(7);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Lift1Bar.setValue(8);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        Lift1Bar.setValue(9);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        Lift1Bar.setValue(10);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Lift1Bar.setValue(1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Lift1Bar.setValue(2);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Lift1Bar.setValue(3);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        Lift1Bar.setValue(11);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        Lift1Bar.setValue(12);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void VVIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VVIPActionPerformed
        VVIPQueue.setValue(VVIPQueue.getValue() + 1);
        VVIPQueue.setString(String.valueOf(VVIPQueue.getValue()));
    }//GEN-LAST:event_VVIPActionPerformed

    private void BlackOpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlackOpsActionPerformed
        BlackOpsQueue.setValue(BlackOpsQueue.getValue() + 1);
        BlackOpsQueue.setString(String.valueOf(BlackOpsQueue.getValue()));
    }//GEN-LAST:event_BlackOpsActionPerformed

    private void ManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManagementActionPerformed
        ManagementQueue.setValue(ManagementQueue.getValue() + 1);
        ManagementQueue.setString(String.valueOf(ManagementQueue.getValue()));
    }//GEN-LAST:event_ManagementActionPerformed

    private void EmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeActionPerformed
        EmployeeQueue.setValue(EmployeeQueue.getValue() + 1);
        EmployeeQueue.setString(String.valueOf(EmployeeQueue.getValue()));
    }//GEN-LAST:event_EmployeeActionPerformed

    private void ProcessQueuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcessQueuesActionPerformed
        //Algorithm starts here
        if (BlackOpsQueue.getValue() > 0) {
            ProcessingStatus.setText("Black Ops\r\n");
        } 
        if (VVIPQueue.getValue() > 0) {
            ProcessingStatus.setText(ProcessingStatus.getText() + "VVIP\r\n");
        } 
        if (ManagementQueue.getValue() > 0) {
            ProcessingStatus.setText(ProcessingStatus.getText() + "Management\r\n");
        } 
        if (BlackOpsEmployeeQueue.getValue() > 0) {
            ProcessingStatus.setText(ProcessingStatus.getText() + "Black Ops Employee\r\n");
        }
        if (EmployeeQueue.getValue() > 0) {
            ProcessingStatus.setText(ProcessingStatus.getText() + "Employee\r\n");
        }
        if (VisitorQueue.getValue() > 0) {
            ProcessingStatus.setText(ProcessingStatus.getText() + "Visitor\r\n");
        }
        if (MaintenanceQueue.getValue() > 0) {
            ProcessingStatus.setText(ProcessingStatus.getText() + "Maintenance\r\n");
        }
        if (CleanerQueue.getValue() > 0) {
            ProcessingStatus.setText(ProcessingStatus.getText() + "Cleaner\r\n");
        }
    }//GEN-LAST:event_ProcessQueuesActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        BlackOpsQueue.setValue(0);
        VVIPQueue.setValue(0);
        ManagementQueue.setValue(0);
        BlackOpsEmployeeQueue.setValue(0);
        EmployeeQueue.setValue(0);
        VisitorQueue.setValue(0);
        MaintenanceQueue.setValue(0);
        CleanerQueue.setValue(0);
        
        BlackOpsQueue.setString("0");
        VVIPQueue.setString("0");
        ManagementQueue.setString("0");
        BlackOpsEmployeeQueue.setString("0");
        EmployeeQueue.setString("0");
        VisitorQueue.setString("0");
        MaintenanceQueue.setString("0");
        CleanerQueue.setString("0");
        
        ProcessingStatus.setText("");
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void BlackOpsEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlackOpsEmployeeActionPerformed
        BlackOpsEmployeeQueue.setValue(BlackOpsEmployeeQueue.getValue() + 1);
        BlackOpsEmployeeQueue.setString(String.valueOf(BlackOpsEmployeeQueue.getValue()));
    }//GEN-LAST:event_BlackOpsEmployeeActionPerformed

    private void RandomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RandomButtonActionPerformed
        // Randomise the queues according to requirements
        //5% VVIP cannot share lifts due to vvip protocol
        //10% Black ops cannot share lifts but lock down mode
        // visitors randomness?
        //10 passengers for each lift maximum
        Random r = new Random();
        
        if(WeekendToggle.isSelected()){
            BlackOpsQueue.setValue(r.nextInt(10));
            VVIPQueue.setValue(r.nextInt(1));
            ManagementQueue.setValue(r.nextInt(5));
            BlackOpsEmployeeQueue.setValue(r.nextInt(10));
            EmployeeQueue.setValue(r.nextInt(20));
            VisitorQueue.setValue(r.nextInt(1));
            MaintenanceQueue.setValue(r.nextInt(100));
            CleanerQueue.setValue(r.nextInt(50)+50);
        }else{
            BlackOpsQueue.setValue(r.nextInt(100));
            VVIPQueue.setValue(r.nextInt(100));
            ManagementQueue.setValue(r.nextInt(100));
            BlackOpsEmployeeQueue.setValue(r.nextInt(100));
            EmployeeQueue.setValue(r.nextInt(100));
            VisitorQueue.setValue(r.nextInt(100));
            MaintenanceQueue.setValue(r.nextInt(100));
            CleanerQueue.setValue(r.nextInt(100));
        }
        
        BlackOpsQueue.setString(String.valueOf(BlackOpsQueue.getValue()));
        VVIPQueue.setString(String.valueOf(VVIPQueue.getValue()));
        ManagementQueue.setString(String.valueOf(ManagementQueue.getValue()));
        BlackOpsEmployeeQueue.setString(String.valueOf(BlackOpsEmployeeQueue.getValue()));
        EmployeeQueue.setString(String.valueOf(EmployeeQueue.getValue()));
        VisitorQueue.setString(String.valueOf(VisitorQueue.getValue()));
        MaintenanceQueue.setString(String.valueOf(MaintenanceQueue.getValue()));
        CleanerQueue.setString(String.valueOf(CleanerQueue.getValue()));
    }//GEN-LAST:event_RandomButtonActionPerformed

    private void VisitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisitorActionPerformed
        VisitorQueue.setValue(VisitorQueue.getValue() + 1);
        VisitorQueue.setString(String.valueOf(VisitorQueue.getValue()));
    }//GEN-LAST:event_VisitorActionPerformed

    private void MaintenanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaintenanceActionPerformed
        MaintenanceQueue.setValue(MaintenanceQueue.getValue() + 1);
        MaintenanceQueue.setString(String.valueOf(MaintenanceQueue.getValue()));
    }//GEN-LAST:event_MaintenanceActionPerformed

    private void CleanerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CleanerActionPerformed
        CleanerQueue.setValue(CleanerQueue.getValue() + 1);
        CleanerQueue.setString(String.valueOf(CleanerQueue.getValue()));
    }//GEN-LAST:event_CleanerActionPerformed

    private void NextStepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextStepActionPerformed
        //Testing of PersonTiming.java class
        ProcessingStatus.setText("");
        Random r = new Random();
        for(int i=0;i<800;i++){
            queue.add(new PersonTiming(r.nextInt(7)+1));
        }
        
        for (int i = 0; i < 2359; i++) {
            for (PersonTiming personTiming : queue) {
                if(personTiming.getTiming()==i){
                    ProcessingStatus.setText(ProcessingStatus.getText()+personTiming.getTypeName()+" "+personTiming.getTiming()+" \r\n");
                }
            }
        }
        
    }//GEN-LAST:event_NextStepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LiftInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LiftInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LiftInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LiftInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LiftInterface().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BlackOps;
    private javax.swing.JButton BlackOpsEmployee;
    private javax.swing.JProgressBar BlackOpsEmployeeQueue;
    private javax.swing.JProgressBar BlackOpsQueue;
    private javax.swing.JButton Cleaner;
    private javax.swing.JProgressBar CleanerQueue;
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton DoorCloseButton;
    private javax.swing.JButton DoorOpenButton;
    private javax.swing.JButton EmergencyAlarmButton;
    private javax.swing.JButton Employee;
    private javax.swing.JProgressBar EmployeeQueue;
    private javax.swing.JButton IntercomButton;
    private javax.swing.JLabel Lift1;
    private javax.swing.JProgressBar Lift1Bar;
    private javax.swing.JProgressBar Lift1Bar1;
    private javax.swing.JProgressBar Lift1Bar2;
    private javax.swing.JProgressBar Lift1Bar3;
    private javax.swing.JProgressBar Lift1Bar4;
    private javax.swing.JLabel Lift2;
    private javax.swing.JLabel Lift3;
    private javax.swing.JLabel Lift4;
    private javax.swing.JLabel Lift5;
    private javax.swing.JButton Maintenance;
    private javax.swing.JProgressBar MaintenanceQueue;
    private javax.swing.JButton Management;
    private javax.swing.JProgressBar ManagementQueue;
    private javax.swing.JButton NextStep;
    private javax.swing.JButton ProcessQueues;
    private javax.swing.JTextArea ProcessingStatus;
    private javax.swing.JButton RandomButton;
    private javax.swing.JProgressBar TotalQueue;
    private javax.swing.JButton VVIP;
    private javax.swing.JProgressBar VVIPQueue;
    private javax.swing.JButton Visitor;
    private javax.swing.JProgressBar VisitorQueue;
    private javax.swing.JToggleButton WeekendToggle;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
